export const countryCode = [
  { value: 'KR', label: 'South Korea' },
  { value: 'DE', label: 'Germany' },
  { value: 'PT', label: 'Portugal' },
  { value: 'DK', label: 'Denmark' },
  { value: 'HR', label: 'Croatia' },
  { value: 'UA', label: 'Ukraine' },
  { value: 'HU', label: 'Hungary' },
  { value: 'MA', label: 'Morocco' },
  { value: 'ID', label: 'Indonesia' },
  { value: 'IE', label: 'Ireland' },
  { value: 'US', label: 'United States' },
  { value: 'EG', label: 'Egypt' },
  { value: 'IL', label: 'Israel' },
  { value: 'UY', label: 'Uruguay' },
  { value: 'IN', label: 'India' },
  { value: 'ZA', label: 'South Africa' },
  { value: 'IT', label: 'Italy' },
  { value: 'MX', label: 'Mexico' },
  { value: 'MY', label: 'Malaysia' },
  { value: 'ES', label: 'Spain' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'AR', label: 'Argentina' },
  { value: 'AT', label: 'Austria' },
  { value: 'AU', label: 'Australia' },
  { value: 'RO', label: 'Romania' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'NO', label: 'Norway' },
  { value: 'RU', label: 'Russia' },
  { value: 'BE', label: 'Belgium' },
  { value: 'FI', label: 'Finland' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'JP', label: 'Japan' },
  { value: 'FR', label: 'France' },
  { value: 'NZ', label: 'New Zealand' },
  { value: 'SA', label: 'Saudi Arabia' },
  { value: 'BR', label: 'Brazil' },
  { value: 'SE', label: 'Sweden' },
  { value: 'SG', label: 'Singapore' },
  { value: 'BY', label: 'Belarus' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'CA', label: 'Canada' },
  { value: 'CH', label: 'Switzerland' },
  { value: 'CL', label: 'Chile' },
  { value: 'GR', label: 'Greece' },
  { value: 'CN', label: 'China' },
  { value: 'CO', label: 'Colombia' },
  { value: 'KZ', label: 'Kazakgstan' },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'TH', label: 'Thailand' },
  { value: 'PE', label: 'Peru' },
  { value: 'CZ', label: 'Czech Republic' },
  { value: 'PL', label: 'Poland' },
  { value: 'TR', label: 'Turkey' },
]
